title: Example
language:
- zh-cn
timezone: UTC
root: /
post_asset_folder: true
highlight:
  enable: true
  line_number: false
per_page: 0

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: egg

less:
  compress: true
